version: '3'
services:
  app:
    image: mcr.microsoft.com/devcontainers/javascript-node:20
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    ports:
      - "8000:8000"
  elasticsearch:
    image: elasticsearch:8.11.0
    container_name: elasticsearch-persitent-container
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
    volumes:
      - esdata1:/usr/share/elasticsearch/data:rw
    ports:
      - "9200:9200"
      - "9300:9300"
volumes:
  esdata1:
    driver: local